### PR TITLE
Add in the outlet cover + texture in main texture file.

### PR DESCRIPTION
**Pull request by l0k1**
Object name is "outletCover". Also added a small bit of texture to the main texture file for it.

### CODE REVIEW

**Comment by l0k1** [comment]
Also, solves https://github.com/NikolaiVChr/flightgear-saab-ja-37-viggen/issues/50

**Comment by NikolaiVChr** [comment]
Thank you, sorry, have been away, and was busy before that with doing controls, so haven't merged this yet.

Will do soon. :)

**Comment by NikolaiVChr** [comment]
Looks awesome Pinto! I have made it move like the manual says, so no more reverser at high speeds.

**Comment by l0k1** [comment]
Woot!

**Pull request merged**
