### PR TITLE
Center pylon fix

### PR DESCRIPTION
**Pull request by l0k1**
Pretty much what the commits say! Pylon is now symmetrical and in dead center.

### CODE REVIEW

**Comment by NikolaiVChr** [comment]
Really nice. Will accept and take a look. :)

**Comment by NikolaiVChr** [comment]
Exported and commited. :)

**Comment by l0k1** [comment]
Nice!
After reviewing for the gun pod, though, I'm going to have to redo it again. =] It looks like that was a pseudo-gun pod or something, not the actual center pylon. It's all good though!

**Comment by NikolaiVChr** [comment]
I think that when the gunpod was attached, the drop-tank was hanging on the gunpod.

**Comment by l0k1** [comment]
I fixed the center pylon to be more anatomically correct, and this is what I was thinking for the gunpod:
image

It all kinda melds together, and will look like one unit (and, minorly, reduce work for future versions of the viggen like the AJ). If you'd rather just have it all as one unit, lemme know and I can do that instead. =]

**EDIT**

Here's what it looks like so far. Need to do the front end, but I can't find any good pictures. i know they exist.

image

**EDIT 2**
Found a good one I can work with. But it's 1:20AM and I need bed, so I'll work on it some more tomorrow.

**Comment by NikolaiVChr** [comment]
If you zoom in on these pics, I think they show everything:

http://postimg.org/gallery/3ieqoi7w0/

Plus page 503 of JA37C manual, gives schematic of the whole gunpod.

**Comment by NikolaiVChr** [comment]
I am making an issue for the gunpod, since this pull request is closed.

**Pull request merged**
