### PR TITLE
Adding fin at back and reshaped and/or moved the pitot tube on the v-…

### PR DESCRIPTION
**Pull request by l0k1**
…stab, the v-stab itself, and the bottom fin.

stuff

### CODE REVIEW

**Comment by NikolaiVChr** [comment]
Awesome!!! Will check it out tomorrow. :)

**Comment by NikolaiVChr** [comment]
Try the livery 61, 48 or 02. I am thinking we have to modify the liveries or the UV map for the backup pitot tube.

**Comment by l0k1** [comment]
Edited the UV map and... textures need to be reworked. Luckily, it's a minor rework, and would take all of 15 minutes to do them all. Lemme know if it's good enough for a pull request.

Here's the liveries in question with the edited UV map.

**Comment by NikolaiVChr** [comment]
That looks very nice!

**Pull request merged**
